ADR for DSP upgrade testing
opendatahub-io/architecture-decision-records pull request #14
Opened 2023-07-05 14:09 UTC by DharmitD

## Description

ADR outlining the upgrade testing strategy for Data Science Pipelines.
## How Has This Been Tested?

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2023-07-05 15:52 UTC, strangiato commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +2. Install Open Data Hub (ODH) Operator.
Has there been any consideration for testing prior to attempting to deploy with ODH?

I would expect there are some unit tests already for the operator already.  Do those need to be executed prior to attempting to deploy with ODH?  Are they already expected to be executed on every PR prior to merging?  If so, does a passing state need to be validated before attempting to deploy with ODH?

Prior to testing with ODH, has the manifest been validated without ODH/KFDef (e.g. `oc apply -k`) to validate that the desired manifests are functional?

2023-07-05 15:52 UTC, strangiato commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +3. Deploy KfDef Core for the First DSPO Version (e.g., v1.7):
The terms `first version`, `second version`, and `target version` are all used throughout the document.  `First` and `second` don't make much sense to me and I would recommend updating these to be something a little more descriptive.

Would `released  version` instead of `first version` and `candidate version` instead of `second`/`target` be more descriptive for what you are trying to say?

2023-07-05 15:52 UTC, strangiato commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +   - Use the KfDef manifest to deploy the core components of the first DSP version (e.g., v1.7).
Has there been any consideration for how this process will change with the ODH Operator redesign?  The KfDef manifest will not longer be utilized so it may be worth talking to the operator team to see how they expect this process to work from their end.  I'm not sure if they are at a phase yet where they know, but this will be something they need to figure out for all components.

2023-07-05 15:52 UTC, strangiato commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +   - Follow the deployment instructions provided by the ODH and DSP documentation for the specified version.
This statement is vague and it is unclear what the goal of this step is.  I don't expect that "follow instructions in documentation" are something that can be codified in a pipeline.  

At this stage I would expect that ODH is already deployed, and an instance of DSPO has already been created.  Is this step then to deploy a Data Science Project and a DSP Application instance?

2023-07-05 15:52 UTC, strangiato commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +7. Automating the Upgrade Testing Process:
The rest of the list reads to me as "these are the steps that should be automated" and this one seems very out of place.  Should this list be part of the number list above, or a separate list outside of the list of steps to be automated?

2023-07-05 15:52 UTC, strangiato commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +## Risks
I would consider the ODH Operator Redesign a risk to this process as I would expect it will change significantly once the redesign is complete.

2023-07-05 20:22 UTC, anishasthana commented
cc @sutaakar @astefanutti

2023-07-06 14:56 UTC, DharmitD commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +2. Install Open Data Hub (ODH) Operator.
> I would expect there are some unit tests already for the operator already. Do those need to be executed prior to attempting to deploy with ODH?

Yes, the operator already has unit tests in place. 

> Prior to testing with ODH, has the manifest been validated without ODH/KFDef (e.g. oc apply -k) to validate that the desired manifests are functional?

Integration tests are also conducted to validate the compatibility and interaction of the DSP components with ODH. Integration tests cover the validation of manifests.

> Are they already expected to be executed on every PR prior to merging? 


Yes, both the unit and integration tests are executed on every PR before merging.

2023-07-06 16:48 UTC, DharmitD commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +3. Deploy KfDef Core for the First DSPO Version (e.g., v1.7):
Makes sense. Updated the document to mention `released` version instead of `first` version and `candidate` version instead of `second/target`

2023-07-06 17:28 UTC, DharmitD commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +   - Use the KfDef manifest to deploy the core components of the first DSP version (e.g., v1.7).
Checked with the operator team on this - Updating manifests will not be supported officially in the operator, but in dev mode, users can update manifest uri, which will allow you to test upgrades. Cc: @VaishnaviHire 

I'll still list out ODH Operator redesign as a risk to the upgrade testing process.

2023-07-06 19:23 UTC, DharmitD commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +   - Follow the deployment instructions provided by the ODH and DSP documentation for the specified version.
> This statement is vague and it is unclear what the goal of this step is. I don't expect that "follow instructions in documentation" are something that can be codified in a pipeline.

The intent of this document is to define a manual upgrade testing process, and mention an approach to automate it. Please refer to the `Non Goals` section.

> At this stage I would expect that ODH is already deployed, and an instance of DSPO has already been created. Is this step then to deploy a Data Science Project and a DSP Application instance?

ODH is deployed at this stage but an instance of DSPO isn't created. We need to deploy a DSPO instance, as listed in  steps #3 to #5.

2023-07-06 19:25 UTC, DharmitD commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +7. Automating the Upgrade Testing Process:
Same as mentioned in the comment earlier, the intent of this document is to specify a manual upgrade testing process, and mention an approach to automate it.

2023-07-10 20:01 UTC, gmfrasca commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +|                |            |
maybe not.  ignore

2023-07-12 21:11 UTC, HumairAK requested changes

2023-07-12 21:11 UTC, HumairAK commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +To perform the upgrade testing process for DSP, follow the steps below:
The wording here is very much sounding like a "how to", I think want to word things in a way that detail our design decisions/intent, for instance: 

```suggestion
The update testing strategy should account for all pre-requisites for deploying DSP, then perform an upgrade, and any follow up tests to confirm the upgrade was successful. The following outlines the design for such a process: 
```

2023-07-12 21:11 UTC, HumairAK commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +   - Set up a GitHub Action workflow to automate the upgrade testing process.
remove mentions of github actions, we want to stay clear of implementation specifics

2023-07-12 21:11 UTC, HumairAK commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +   - Determine the candidate version for the DSP upgrade (e.g., v1.17).
The candidate need not be a version, we want to test upgrade upon a commit essentially, this can be `main` even, or some commit in history, or a tag, latest in branch, etc.

2023-07-12 21:11 UTC, HumairAK commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +   - Follow the deployment instructions provided by the ODH and DSP documentation for the specified version.
I think we can just say "Deploy a DSPA instance", we don't need to say any more here about documentation, or how to do it. Same for step 5.

2023-07-12 21:11 UTC, HumairAK commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +   - Collect the test results, including logs, error messages, and any
> error messages, and any 

and any...???

2023-07-13 16:26 UTC, DharmitD commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +   - Follow the deployment instructions provided by the ODH and DSP documentation for the specified version.
Updated as suggested.

2023-07-13 16:27 UTC, DharmitD commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +* Automate the upgrade testing process using GitHub Actions.
Updated as suggested.

2023-07-13 16:27 UTC, DharmitD commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +To perform the upgrade testing process for DSP, follow the steps below:
Updated as suggested.

2023-07-13 16:28 UTC, DharmitD commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +   - Collect the test results, including logs, error messages, and any
Oops, not sure how that got deleted. Updated to complete the sentence now.

2023-07-13 16:28 UTC, DharmitD commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +3. Deploy KfDef Core for the released DSPO Version (e.g., v1.7):
Updated as suggested.

2023-07-18 20:39 UTC, HumairAK commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +   - Determine the candidate version for the DSP upgrade.
let's say candidate version/tag/branch/commit, we want flexibility to use this testing framework on all of these upon request/input/trigger/etc.

2023-07-18 20:56 UTC, HumairAK commented
/lgtm 

@gmfrasca / @amadhusu  / @gregsheremeta can you also review/sign off on this

2023-07-18 21:22 UTC, DharmitD commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +   - Determine the candidate version for the DSP upgrade.
Done, upgraded to mention that the candidate version could be a tag, branch or a commit.

2023-07-18 21:37 UTC, HumairAK commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +|                               |            |       |
Humair K.  | July 18th, 2023 | --

2023-07-18 21:44 UTC, DharmitD commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +|                               |            |       |
Done. Thank you!

2023-07-19 13:44 UTC, amadhusu reviewed
/lgtm

2023-07-19 13:54 UTC, amadhusu commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +| Humair K.      | July 18th, 2023 | --    |
I don't know if its required but 
Achyut M. | July 19th 2023

2023-07-20 21:37 UTC, gregsheremeta commented
/lgtm

2023-07-20 21:42 UTC, gmfrasca commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +7. Automating the Upgrade Testing Process:
I think what @strangiato is mentioning is that the steps 1-6 are defined and explict actionionable procedure, but item 7 is a suggestion for future work.  Could we make this a subheading instead (like `## Automation Considerations`)?

2023-07-20 23:15 UTC, DharmitD commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +7. Automating the Upgrade Testing Process:
Done, created a separate subheading for Automation Considerations.

2023-07-21 07:12 UTC, anishasthana commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +   - Execute tests specific to testing the success of the DSP version upgrade. Examples of test cases could include checking if resources such as DSPO and DSPA deployments, ServiceMonitors, etc., com
What about already running pipelines?

2023-07-21 18:50 UTC, gmfrasca commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +| Greg S.        | July 20th, 2023 | --    |
```suggestion
| Greg S.        | July 20th, 2023 | --    |
| Giulio F.      | July 21st, 2023 | --    |
```

2023-07-24 17:07 UTC, DharmitD commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +   - Execute tests specific to testing the success of the DSP version upgrade. Examples of test cases could include checking if resources such as DSPO and DSPA deployments, ServiceMonitors, etc., com
Added this query to the Open Questions section.

2023-07-24 17:08 UTC, DharmitD commented
/lgtm

2023-07-24 17:09 UTC, anishasthana commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +1. Impact on Running Pipelines:
@DharmitD Can you create a follow-on issue for this to make sure we don't lose track? And link to that from this README

2023-07-24 17:11 UTC, HumairAK commented
/hold until we figure out where to add this adr

2023-07-24 18:13 UTC, DharmitD commented on ODH-ADR-0007-data-science-pipelines-upgrade-testing-strategy.md
> +1. Impact on Running Pipelines:
@anishasthana Done, created a follow-on issue here: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/217

2023-07-24 19:12 UTC, anishasthana approved these changes

2023-07-25 20:38 UTC, HumairAK commented
this adr should have sufficient reviews/sign offs to accept it
/lgtm
/approve

@LaVLaS can we have this merged?

2023-07-25 20:41 UTC, gregsheremeta commented
/hold

sorry, can we avoid reusing numbers?

ADR-xxxx already exists.  Can we use ADR-DSP prefix?

(nitpick: would prefer we start at 1 too. My intention with 0 was for a meta-document, not an actual ADR)

2023-07-25 21:17 UTC, gregsheremeta commented
/unhold

2023-08-01 15:37 UTC, gregsheremeta approved these changes

2023-08-01 15:38 UTC, merged