ADR 0010 ODH/Caikit/TGIS integration
opendatahub-io/architecture-decision-records pull request #20
Opened 2023-09-26 18:33 UTC by Xaenalt

Overview of the architecture and diagram of the ODH+Caikit+TGIS architecture

## Description

## How Has This Been Tested?

## Merge criteria:

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

2023-09-26 19:08 UTC, Xaenalt commented
@jwforres @etirelli PTAL

2023-09-26 19:32 UTC, anishasthana requested changes

2023-09-26 19:32 UTC, anishasthana commented on ODH-ADR-0010-caikit-tgis-architecture.md
> +| RedHat Distributed Workloads Team | Anish Asthana                 |      | Yes       |
```suggestion
| RedHat Distributed Workloads Team | Anish Asthana, Antonin Stefanutti                 |      | Yes       |
```

2023-09-26 20:13 UTC, anishasthana commented on ODH-ADR-0010-caikit-tgis-architecture.md
> +| RedHat Distributed Workloads Team | Anish Asthana                 |      | Yes       |
@astefanutti fyi

2023-09-26 20:39 UTC, Xaenalt commented
> Imo we should have the lucidchart be included in this ADR itself

It's linked in "other docs" and in the "references" section, is there a way to include it more generally?

2023-10-05 13:14 UTC, astefanutti commented
> > Imo we should have the lucidchart be included in this ADR itself
> 
> It's linked in "other docs" and in the "references" section, is there a way to include it more generally?

I'd recommend exporting the diagram to SVG, commit the SVG file along the ADR, and include the SVG into the ADR  markdown file as suggested by @anishasthana.

Also as Lucidchart is being retired, I'd recommend to export the diagram in VSDX format so it can be imported into other diagramming solutions like draw.io.

2023-10-06 20:19 UTC, anishasthana commented on ODH-ADR-0010-caikit-tgis-architecture.md
> +| Status         | Accepted                                                                                                                     |
Why is this saying accepted already? :-)

2023-10-10 16:44 UTC, israel-hdez commented on ODH-ADR-0010-caikit-tgis-architecture.md
> +This ADR describes the architecture of the joint IBM-RedHat integration of ODH and Caikit/TGIS into the AI stack.
Are we good mentioning company ascription here?

It doesn't seem relevant for ODH.

2023-10-25 17:53 UTC, Xaenalt commented
![RHOAI + Caikit Architecture v1 0](https://github.com/opendatahub-io/architecture-decision-records/assets/8479010/cf198e5b-4e11-4d65-bec9-3c1ed5df4069)

2024-07-18 03:17 UTC, closed without merging