RHOAIENG-3943 Update Model Registry documentation
opendatahub-io/architecture-decision-records pull request #34
Opened 2024-03-28 09:13 UTC by tarilabs

## Description
I followed same style per https://issues.redhat.com/browse/RHOAIENG-3946

I've used as sources:
- "Model Registry Architecture" 
- "Model Registry Proposal" 
- https://issues.redhat.com/browse/RHOAIENG-1071 
- https://github.com/opendatahub-io/model-registry-bf4-kf/issues/249 
- https://github.com/opendatahub-io/odh-model-controller/pull/135

Since "Model Registry Tenancy Proposal" is still under finalization I didn't include it yet in the current PR, we can expand on it later once the ADR is approved.

## How Has This Been Tested?

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2024-03-28 13:34 UTC, etirelli requested changes
made some minor editorial comments, but I suggest rewording the whole document to reflect what is the model server component (present tense), instead of what is intended for the future.

2024-03-28 13:34 UTC, etirelli commented on architecture/components/model-registry/README.md
> +- Avoid reinvention unless it is mandatory
since this is the architecture documentation, I would remove lines 24 and 26 above as they are more relevant for community and development

2024-03-28 13:34 UTC, etirelli commented on architecture/components/model-registry/README.md
> +Google community project [ML-Metadata](https://github.com/google/ml-metadata) will be used as the core component to build the Model Registry. ML-Metadata provides a very extensible schema that is gen
s/"will be used"/"is used"? 
s/"we intend to use"/"we use"?

2024-03-28 13:37 UTC, tarilabs commented on architecture/components/model-registry/README.md
> +We envision this to be more of a backing store for various stages of MLOps that can log user flow of a model development and deployment. The model registry will meet a data scientist's need to be abl
```suggestion
The model registry is a backing store for various stages of MLOps that can log user flow of a model development and deployment. The model registry meets a data scientist's need to be able to visualize a model’s lineage and trace back the training executions, parameters, metrics, etc. It also help deployment engineers visualize model pipeline events, actions, progress through deployment stages, etc. 
```

2024-03-28 13:38 UTC, tarilabs commented on architecture/components/model-registry/README.md
> +- Associate metadata from as training, experimentation, studies and their metrics, with a model
```suggestion
- Associate metadata from training, experimentation, studies and their metrics, with a model
```

2024-03-28 13:38 UTC, tarilabs commented on architecture/components/model-registry/README.md
> +- Management of model to different deployment environments
```suggestion
- Management of model for multiple deployment environments
```

2024-03-28 13:41 UTC, tarilabs commented on architecture/components/model-registry/README.md
> +- Avoid reinvention unless it is mandatory
done with https://github.com/opendatahub-io/architecture-decision-records/pull/34/commits/2662f268e63dd739be10889d1e4b1c7295587db6

2024-03-28 13:41 UTC, tarilabs commented on architecture/components/model-registry/README.md
> +Google community project [ML-Metadata](https://github.com/google/ml-metadata) will be used as the core component to build the Model Registry. ML-Metadata provides a very extensible schema that is gen
```suggestion
Google community project [ML-Metadata](https://github.com/google/ml-metadata) is used as the core component to build the Model Registry. ML-Metadata provides a very extensible schema that is generic, similar to a key-value store, but also allows for the creation of logical schemas that can be queried as if they were physical schemas. Those can be manipulated using their bindings in the Python library. We use this model to extend and provide metadata storage services for model serving, also known as Model Registry.
```

2024-03-28 13:58 UTC, tarilabs commented
> made some minor editorial comments, but I suggest rewording the whole document to reflect what is the model server component (present tense), instead of what is intended for the future.

thank you for the feedback @etirelli , I believe I rewritten all future tense sentences I could find to present tense with https://github.com/opendatahub-io/architecture-decision-records/pull/34/commits/4dd3c077b0813126372aa2044da47b7931cd6f31

2024-04-15 11:58 UTC, etirelli approved these changes

2024-04-15 11:59 UTC, merged