Add AI Edge architecture diagram
opendatahub-io/architecture-decision-records pull request #40
Opened 2024-04-17 14:31 UTC by LaVLaS

Add architecture diagram for AI Edge.

Draw.io files will be stored in opendatahub-io/ai-edge while the development of the project is ongoing and architecture will change with feature updates

2024-04-23 13:29 UTC, adelton requested changes

2024-04-23 13:29 UTC, adelton commented on architecture/components/edge/README.md
> +MLOps Pipelines and integration with [GitOps](https://www.redhat.com/en/topics/devops/what-is-gitops) workflows to deliver and serve AI/ML models to Edge environments.
Could we explain why it is that we add integration with the GitOps workflows for the Edge environments and why the GitOps integration is not a generic RHOAI feature?

2024-04-23 13:29 UTC, adelton commented on architecture/components/edge/README.md
> +### Inference Container
Should this be `Inference Container Image`? The next sentence starts with "Container image ..." which is weird for a section which talks about a container.

2024-04-23 13:29 UTC, adelton commented on architecture/components/edge/README.md
> +  model inferencing will be available in any environment where OCI container workflows are supported.
Could we explain why it's important to have the inference container image for the Edge deployments but the same is not important for non-Edge (== on the OpenShift AI OCP cluster) situations?

2024-04-23 13:29 UTC, adelton commented on architecture/components/edge/README.md
> +* Fetch the model from a storage location(Object Storage, Git, Model Registry,...),
Space before the left parenthesis. Space after the comma.

2024-04-23 13:29 UTC, adelton commented on architecture/components/edge/README.md
> +OpenShift Pipelines provide the orchestration we use to:
Should we be explicit in saying this is an operator?

2024-04-23 13:29 UTC, adelton commented on architecture/components/edge/README.md
> +### OpenShift Pipelines
Should we use the full product name as shown in the OperatorHub: `Red Hat OpenShift Pipelines`?

2024-04-23 13:29 UTC, adelton commented on architecture/components/edge/README.md
> +* The near edge environment is represented by separate OpenShift cluster(s) where AI/ML models can be configured and deployed using GitOps workflows
Missing full stop while the other bullet points have them.

2024-04-23 13:29 UTC, adelton commented on architecture/components/edge/README.md
> +
Inconsistent ends of the bullet points. The list above seems to use full stops, here is one command and no ending punctuation mark on others.

2024-04-23 13:29 UTC, adelton commented on architecture/components/edge/README.md
> +* Test the inferencing container in a staging environment that is representative of the final production environment where the inference server will be running
Is this about the `test-container-deploy`? Can we really make the claim that that Container is in any way representative of the final production environment?

2024-04-23 13:29 UTC, adelton commented on architecture/components/edge/README.md
> +### GitOps Operator
Should we use the full product name as shown in OperatorHub: `Red Hat OpenShift GitOps`?

2024-04-23 13:29 UTC, adelton commented on architecture/components/edge/README.md
> +### Open Telemetry
Should this be spelled without the space?

2024-04-23 13:29 UTC, adelton commented on architecture/components/edge/odh-edge-architecture-high-level-architecture.png
Please `s/ArgoCD/Argo CD/g`.

2024-04-30 05:38 UTC, LaVLaS commented on architecture/components/edge/README.md
> +OpenShift Pipelines provide the orchestration we use to:
We only reference "OpenShift Pipelines operator" as the installation method to install OpenShift Pipelines(Tekton) from OperatorHub.

2024-04-30 05:45 UTC, LaVLaS commented on architecture/components/edge/README.md
> +### GitOps Operator
> Should we use the full product name as shown in OperatorHub: `Red Hat OpenShift GitOps`?

That would a difference between the product "Red Hat OpenShift GitOps" that deploys ArgoCD vs the reference here to the pattern of a GitOps repository.

2024-04-30 06:01 UTC, adelton commented on architecture/components/edge/README.md
> +### GitOps Operator
But this section is titled "GitOps Operator". There is no such thing. Did you want to say "GitOps workflow" or something similar then?

2024-05-02 04:11 UTC, LaVLaS commented on architecture/components/edge/README.md
> +### Open Telemetry
Correct. This was a typo.

2024-05-02 13:04 UTC, LaVLaS commented on architecture/components/edge/README.md
> +### GitOps Operator
Ahhh. You are correct. In reading your question, I was focused on line 28 in the GitHub highlight but `GitOps workflow` is more appropriate

2024-05-06 05:52 UTC, LaVLaS commented on architecture/components/edge/README.md
> +  model inferencing will be available in any environment where OCI container workflows are supported.
I added an extra sentence to address your comment. PTAL

2024-05-06 06:25 UTC, LaVLaS commented on architecture/components/edge/README.md
> +### Inference Container
I removed `image` from the start of the description so that the references to `Inference Container Image` are used when referencing process of building OR transporting of the container image.

2024-05-06 06:41 UTC, LaVLaS commented on architecture/components/edge/README.md
> +MLOps Pipelines and integration with [GitOps](https://www.redhat.com/en/topics/devops/what-is-gitops) workflows to deliver and serve AI/ML models to Edge environments.
I added an additional statement to the `GitOps Workflows` section about integration. 

> ...why the GitOps integration is not a generic RHOAI feature?

I added a comment for this to reflect that AI Edge is to understand Edge workflows to discover where we can add OpenShift AI features to extend from core --> edge

2024-05-06 07:12 UTC, LaVLaS commented on architecture/components/edge/README.md
> +* Test the inferencing container in a staging environment that is representative of the final production environment where the inference server will be running
The intent was to reflect the staging environment would be representative of the final production environment but I changed the text focus on running tests in a "staging environment"

2024-05-06 10:09 UTC, adelton commented on architecture/components/edge/README.md
> +### Inference Container
I'm still not convinced.

Yes, baking the model in to the serving runtime image allows for "control over the security, stability and versions" but if that is desired, its can be just as desired and used in resource unrestricted environments and in the core ODH/RHOAI cluster.

IOW, even if this was PoC-demonstrated in the https://github.com/opendatahub-io/ai-edge repo, I don't think that this belongs to the edge components of the whole architecture and should live as a separate functionality.

2024-05-06 10:11 UTC, adelton commented on architecture/components/edge/README.md
> +  model inferencing will be available in any environment where OCI container workflows are supported.
I'm still not convinced.

Yes, baking the model in to the serving runtime image allows for "control over the security, stability and versions" but if that is desired, its can be just as desired and used in resource unrestricted environments and in the core ODH/RHOAI cluster.

IOW, even if this was PoC-demonstrated in the https://github.com/opendatahub-io/ai-edge repo, I don't think that this belongs to the edge components of the whole architecture and should live as a separate functionality.

2024-05-06 10:17 UTC, adelton commented on architecture/components/edge/README.md
> +MLOps Pipelines and integration with [GitOps](https://www.redhat.com/en/topics/devops/what-is-gitops) workflows to deliver and serve AI/ML models to Edge environments.
In this repo (as opposed to https://github.com/opendatahub-io/ai-edge), shouldn't we focus on the resulting architecture of the overall project/product, not on the partial efforts (projects) that explored or introduced the functionality?

In other words, shouldn't the GitOps functionality / integration be described in these architecture documents as completely independent of the edge?

2024-05-15 05:26 UTC, LaVLaS commented
Closing this as we need to review the feature set that will be included as part of an Edge offering.  The arch diagrams will still be located at opendatahub-io/ai-edge

2024-05-15 05:30 UTC, closed without merging