Upgrade manifests to kustomize v5
opendatahub-io/architecture-decision-records pull request #43
Opened 2024-05-07 11:35 UTC by ykaliuta

Components manifests update to v5 proposal.

## Description

## How Has This Been Tested?

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2024-05-21 06:41 UTC, ykaliuta commented
@gmfrasca @franciscojavierarceo @danielezonca @terrytangyuan @andrewballantyne @LaVLaS @harshad16 @dhirajsb @ruivieira

2024-05-28 12:46 UTC, etirelli requested changes
Should this ADR be moved under the platform/operator folder? Also, can you please rename the file with the proper ADR number?

2024-05-28 19:16 UTC, andrewballantyne commented on operator/ODH-ADR-Operator-0004-kustomize-v5.md
> +their manifests independently in their own pace.
Is this basically saying "you don't have to do anything"?

2024-05-28 19:16 UTC, andrewballantyne commented on operator/ODH-ADR-Operator-0004-kustomize-v5.md
> +* No exact recipe how to convert old manifests to the new version.
I'm confused what this ADR's goal is... "we are upgrading to v5 -- but not going to tell you what you need to support and also, you don't have to do anything?"

2024-05-28 19:33 UTC, ykaliuta commented on operator/ODH-ADR-Operator-0004-kustomize-v5.md
> +* No exact recipe how to convert old manifests to the new version.
I would like to leave freedom to the component owners to cook their manifests as they wish as soon as they:
1) do not use obsoleted functionality;
2) keep interface with the operator (params.env).

Replacing `vars` can be tricky. Kustomize provides autoconverter but it did not work well in most of the cases.

2024-05-28 19:33 UTC, ykaliuta commented on operator/ODH-ADR-Operator-0004-kustomize-v5.md
> +their manifests independently in their own pace.
No :) Keeping interface the same does not mean keeping implementation the same. Manifests should not use obsoleted keywords.

2024-05-29 00:50 UTC, harshad16 commented on operator/ODH-ADR-Operator-0004-kustomize-v5.md
> +* No exact recipe how to convert old manifests to the new version.
The wording of the goal is broad, we mention, the goal is to define requirements, are we only suggesting update of params.env or update of any deprecated variable for kustomize ?

2024-05-29 02:10 UTC, terrytangyuan commented on operator/ODH-ADR-Operator-0004-kustomize-v5.md
> +manifests to be complaint to current (v5) kustomize version
Do you mean "compliant"?

2024-05-29 02:10 UTC, terrytangyuan commented on operator/ODH-ADR-Operator-0004-kustomize-v5.md
> +  component, like fail to update images.
Could you elaborate?

2024-05-29 02:10 UTC, terrytangyuan commented on operator/ODH-ADR-Operator-0004-kustomize-v5.md
> +kustomize v5 it is possible to use it with the same result:
What do you mean by "it is possible to use it with the same result"?

2024-05-29 07:52 UTC, ykaliuta commented on operator/ODH-ADR-Operator-0004-kustomize-v5.md
> +manifests to be complaint to current (v5) kustomize version
> Do you mean "compliant"?

Yes, sure, thanks :)

2024-05-29 07:55 UTC, ykaliuta commented on operator/ODH-ADR-Operator-0004-kustomize-v5.md
> +* No exact recipe how to convert old manifests to the new version.
> The wording of the goal is broad, we mention, the goal is to define requirements, are we only suggesting update of params.env or update of any deprecated variable for kustomize ?

Yes, I agree, using up-to-date kustomize configuration sounds as a requirement from operator as well. 
Do you suggest to mention the obsoleted parts here? (I put links just in the references)

2024-05-29 08:01 UTC, ykaliuta commented on operator/ODH-ADR-Operator-0004-kustomize-v5.md
> +  component, like fail to update images.
> Could you elaborate?

At this moment (IIUC it will change with Konflux) operators gets "RELATED_IMAGE_*" variables from environment (set by CPaasS), edits `params.env` for component and runs kustomize to get resulting manifests. `params.env` is used to create a ConfigMap and kustomize functionality (`vars` for older versions, `replacements` for the new one) to make replacements for the actual images (there is usecase with namespace but it basically works the same way).

If component does not use `params.env` for example. Like puts the image names directly to the manifests, operator will not substitute it.

2024-05-29 08:03 UTC, ykaliuta commented on operator/ODH-ADR-Operator-0004-kustomize-v5.md
> +kustomize v5 it is possible to use it with the same result:
> What do you mean by "it is possible to use it with the same result"?

I mean that on component<->operator communication level, operator still just edits the file (`params.env`) and component's kustomize produce proper manifests. Regardless if it's some variable substitution or field replacement.

2024-05-29 20:32 UTC, andrewballantyne commented on operator/ODH-ADR-Operator-0004-kustomize-v5.md
I'm still unclear what the intent of this ADR is -- "there are some changes -- you need to support them" doesn't sound so much like an ADR but a statement of deprecation of old features -- which this ADR document doesn't seem to be listing (unless I am missing something).

I'm not an expert on Kustomize, and as far as I understood this ADR -- we are compatible with the upgrade?

2024-06-03 08:00 UTC, ykaliuta commented on operator/ODH-ADR-Operator-0004-kustomize-v5.md
The intend of the ADR is to define that part of component/operator communication and provide information to the component owners what rules the manifests must obey to keep system working, this is architectural decision since it is related to all the parties (components and the operator). The original plan, if you check the Epic, what to create another way of the communication, so the ADR would described that.

Most of the components use obsoleted functionality and must be upgraded. I even provided the example in the Epic. They are compatible with the operator, but not with the updated kustomize.

I hope it answers your questions.

2024-06-03 12:06 UTC, andrewballantyne commented on operator/ODH-ADR-Operator-0004-kustomize-v5.md
The best I have taken away from this is "other components" will need to do changes. The Dashboard sounds like it's compatible with `params.env` and I'm unclear what I need to do here to move us forward. I'll look at the epic again, once I find it in Jira, and likely close out the Dashboard Task as I don't see a clear plan to move Dashboard forward. We have plenty on our backlog, this ADR is not clear on what is needed, and if something is truly needed, I guess I'll find out down the line.

2024-06-03 12:13 UTC, ykaliuta commented on operator/ODH-ADR-Operator-0004-kustomize-v5.md
@andrewballantyne Again, dashboard uses vars, patchesJson6902, commonLabels which are obsoleted in kustomize v5.

2024-06-03 12:57 UTC, andrewballantyne approved these changes
Thank you for answering my questions, the Dashboard team will prioritize the effort.

2024-07-17 03:16 UTC, closed without merging