[RHOAIENG-1104] Update annotation doc with storage class info
opendatahub-io/architecture-decision-records pull request #61
Opened 2024-08-20 15:27 UTC by jpuzz0

https://issues.redhat.com/browse/RHOAIENG-1104

## Description
Added storage class annotation documentation for new metadata to be used in the dashboard.

## Merge criteria:
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2024-08-20 16:36 UTC, DaoDaoNoCode requested changes

2024-08-20 16:36 UTC, DaoDaoNoCode commented on documentation/components/dashboard/k8sLabelsAndAnnotations.md
> +[`opendatahub.io/sc-config`]: #storage-classes
```suggestion
[`opendatahub.io/sc-config`]: #opendatahubiosc-config
```
So that your last changed line could lead to the correct section

2024-08-20 17:54 UTC, Gkrumbach07 commented on documentation/components/dashboard/k8sLabelsAndAnnotations.md
> +Admins can use this annotation to define storage class attributes to differentiate between other storage classes. This metadata can be leveraged to utilize non-Openshift default storage classes.
make it clear that this metadata is for dashboard UI use only and does not affect the Openshift defaults. Also it should not be leveraged by admins but used by the UI to manage the ODH default class and the if the class is enabled in the UI.

2024-08-20 19:47 UTC, jpuzz0 commented on documentation/components/dashboard/k8sLabelsAndAnnotations.md
> +Admins can use this annotation to define storage class attributes to differentiate between other storage classes. This metadata can be leveraged to utilize non-Openshift default storage classes.
Updated

2024-08-20 19:50 UTC, DaoDaoNoCode approved these changes
/lgtm

2024-08-21 14:54 UTC, Gkrumbach07 commented on documentation/components/dashboard/k8sLabelsAndAnnotations.md
> +  * [`opendatahub.io/sc-config`] - (optional, typed in)
should be something like 

```suggestion
  * [`opendatahub.io/sc-config`] - (managed by the UI) a JSON Blob of storage class metadata
```

2024-08-21 14:55 UTC, Gkrumbach07 commented on documentation/components/dashboard/k8sLabelsAndAnnotations.md
> +This annotation is configured by admins. It is also viewable/editable in the Dashboard by admins via `Settings > Storage classes`.
you dont need this description here becuase they are an OpenShift concept

2024-08-21 16:42 UTC, etirelli approved these changes

2024-08-21 16:42 UTC, merged