add ADR for auth CRD
opendatahub-io/architecture-decision-records pull request #70
Opened 2024-10-22 08:29 UTC by StevenTobin

## Description

Add an ADR recording the decision to add an auth CRD.
## How Has This Been Tested?

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2024-10-22 12:25 UTC, lburgazzoli commented
In term of naming, as part of the [RHOAIENG-10498](https://issues.redhat.com/browse/RHOAIENG-10498), we are going to introduce a new API group  `services.opendatahub.io` for shared services / concerns [RHOAIENG-13009](https://issues.redhat.com/browse/RHOAIENG-13009) so it could be something like:

```yaml
apiVersion: services.opendatahub.io/v1alpha1
name: Auth
```

2024-10-22 13:58 UTC, zdtsw commented
the ADR is for "we need a new CRD in Operator to handle auth releated work" but nothing defined what need/should be captured in this CRD for now, except it will handle adminGroup
is my understanding correct?

2024-10-22 14:21 UTC, etirelli commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-auth-crd.md
> +* Naming of the new CRD.
In order to move forward with this ADR, it would be best to have a decision on the name of the CRD, and a definition of the structure. Also, can you add some information on how the components would then leverage the CRD to overcome the current deficiencies?

2024-10-22 14:21 UTC, etirelli requested changes
As per my comment.

2024-10-22 14:36 UTC, VaishnaviHire commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-auth-crd.md
> +A new API is added to the operator in the form of an *DSCAuth* (Naming to be decided) CRD. This will initially handle a list of adminGroups which the operator will reconcile for access to dashboard U
Will this be something that will only be included when Dashboard component is enabled?

If not, should this instead be an internal api with configuration fields exposed in DSCI?

2024-10-25 08:11 UTC, StevenTobin commented
> In term of naming, as part of the [RHOAIENG-10498](https://issues.redhat.com/browse/RHOAIENG-10498), we are going to introduce a new API group `services.opendatahub.io` for shared services / concerns [RHOAIENG-13009](https://issues.redhat.com/browse/RHOAIENG-13009) so it could be something like:
> 
> ```yaml
> apiVersion: services.opendatahub.io/v1alpha1
> name: Auth
> ```

This makes sense, I'll add that. Moving it under this services API will reduce friction later.

2024-10-25 13:11 UTC, lphiri commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-auth-crd.md
> +There is a growing need for the ODH operator to handle authentication for the platform. OIDC is not handled gracefully over the entire system, and there are use cases where individual components are
```suggestion
There is a growing need for the ODH operator to provide centralized authentication and authorization services for the platform.  The near term needs are :

-  Add support for managing user groups. Currently this  is  managed by the Dashboard component and needs to be centralized.
-  Prepare for upcoming for changes to handle OCP Platform support for external OIDC authentication

Longer term,  this API and its controller will be enhanced to handle additional RBAC configuration currently handled in the Dashboard component, such as creating roles and role bindings.

Centralising auth concerns will simplify the architecture of auth features, security and ease of use of these features for users.

```

2024-10-25 14:31 UTC, lphiri commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-auth-crd.md
> +## Open Questions
Can we add discussions here about how we migrate/upgrade current dashboard implementation?
Do we deprecate  Dashboard userGroups over some period, or do we just switch right away given the Dashboard config API is alpha? 
@andrewballantyne

2024-10-25 14:48 UTC, andrewballantyne commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-auth-crd.md
> +## Open Questions
@csams and I were talking about that. I would recommend a cold turkey switchover; it's alpha on our side, so I don't imagine we have a reliance here in our support to migrate slowly... but I don't know how we can cleanly do that tbh. 

The cold turkey approach is done like so (I would guess):
* Upgrade available
* User invokes / auto upgrade invokes
* Operator would need to create new location (likely a new CRD & CR? or maybe just a CRD field in DSCI or something?)
* Copy the data from OdhDashboardConfig over
* Invoke Component upgrade (Dashboard at least)
* Dashboard CRD drops the field -- the CR loses the values
* We are upgraded

If the order is not pretty much what is above (given infrastructures of the operator today) then I imagine we need to slowly migrate over release(s) and I imagine many (EUS/Stable/Fast all need to have 1 with the migration effort).

cc @etirelli FYI

2024-10-28 11:39 UTC, lphiri reviewed
Suggested some wording tweaks.

2024-11-21 09:02 UTC, StevenTobin commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-auth-crd.md
> +## Open Questions
I added some text around the upgrade strategy we discussed in a seperate meeting.

2024-11-21 14:00 UTC, andrewballantyne commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-auth-crd.md
> +```
You don't speak to it here -- is this a singleton like DSC and DSCI or would they create multiple? If they can, is there any benefit today for that or is that for "future use-cases"?

2024-11-22 11:48 UTC, StevenTobin commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-auth-crd.md
> +```
Yep, this is intended to be a singleton, I've added that to the ADR now.

2024-11-22 11:50 UTC, lphiri approved these changes
LGTM

2024-11-22 12:00 UTC, lburgazzoli commented
LGTM

2024-11-22 12:01 UTC, lburgazzoli approved these changes

2024-11-22 14:14 UTC, csams requested changes
I have a couple questions about naming and making sure the scope is clear.

2024-11-22 14:14 UTC, csams commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-auth-crd.md
> +    adminGroups: []
Let's include the allowedGroups from dashboard config in the example just so the intent is explicit if we're going to disable it in their CR.

2024-11-22 14:14 UTC, csams commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-auth-crd.md
> +kind: Auth
@lphiri @etirelli Should we combine authn and authz concerns in this CR, or should we separate them and give this one a more specific name like `Authz` or `Authorization`?

2024-11-22 14:14 UTC, csams commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-auth-crd.md
> +A new  API is added to the operator in the form of an auth CRD in the services api group. This will initially handle a list of adminGroups which the operator will reconcile for access to dashboard UI
A comment below mentions disabling the ability to edit the dash config stanza that I think includes both admin group and allowed groups.  Are we doing both?

2024-11-22 14:22 UTC, StevenTobin commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-auth-crd.md
> +    adminGroups: []
:+1:  good point. I've added that.

2024-11-22 14:22 UTC, StevenTobin commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-auth-crd.md
> +A new  API is added to the operator in the form of an auth CRD in the services api group. This will initially handle a list of adminGroups which the operator will reconcile for access to dashboard UI
Good point. I've made it more explicit.

2024-11-22 15:53 UTC, csams commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-auth-crd.md
> +kind: Auth
If we keep the 1 CR, maybe namespace the authn/z concerns beneath the spec: `spec.authn`, `spec.authz`.

2024-11-22 20:43 UTC, andrewballantyne approved these changes

2024-12-02 08:22 UTC, StevenTobin commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-auth-crd.md
> +kind: Auth
A single CR for both authz and authn would make more sense I think than seperating them, and namespacing like you point out makes it clearer which setting in the CR relates to which concern.

I would agree for futureproofing.

2024-12-06 06:41 UTC, zdtsw commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-auth-crd.md
> +apiVersion: services.opendatahub.io/v1alpha1
after the lastest change this should be updated to 
`apiVersion: services.platform.opendatahub.io/v1alpha1`

2024-12-06 13:20 UTC, lphiri approved these changes

2024-12-06 13:22 UTC, merged