Components version mapping adr
opendatahub-io/architecture-decision-records pull request #72
Opened 2024-10-31 14:09 UTC by Sara4994

## Description

## How Has This Been Tested?

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2024-11-01 13:42 UTC, VaishnaviHire commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +| ODH Platform Team             | Saravana Srinivasan   |   | ? |
I think for key contacts here add @lburgazzoli @lphiri

2024-11-01 13:54 UTC, zdtsw commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +| Status         | Approved                         |
already approved?

2024-11-01 13:54 UTC, zdtsw commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +# Open Data Hub - Map component upstream versions to RHOAI releases
should it be ODH releases?

2024-11-01 13:54 UTC, zdtsw commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +This document is intended to outline the design decisions made to map upstream versions of components that are supported by Data Science Cluster to RHOAI releases.
same here and below: if we are not only enable this for RHOAI, should ODH be used than RHOAI, same to all other ADR

2024-11-01 13:54 UTC, zdtsw commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +- This information can then be read by the Dashboard UI via API and displayed in "About" modal of the UI.
i do not think this need to be as a goal.

2024-11-01 13:54 UTC, zdtsw commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +- Create UX designs to display the list of information shared by the operator.
same as here, this related to a specific feature in Dashboard.

2024-11-01 13:54 UTC, zdtsw commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +| ODH Platform Team             | Saravana Srinivasan   |   | ? |
should component team leads also set to be stakeholder?

2024-11-01 14:28 UTC, grdryn commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +- Expecting components to create and maintain an "releases.yaml" file in their repositories particularly in manifest or config folders. The yaml can contain release details of the upstreams in format
The proposed file structure has a top-level key (currently `releases`) to hold the list. I like this approach as it allows for further information to be included in future (where an immediate list at the top level wouldn't have been as flexible). If any information was to be added in future though, would the filename `releases.yaml` still always make sense? 

I'd like to hear other opinions on this. I wonder if something more generic like `odh_metadata.yaml` would be better?

2024-11-01 14:45 UTC, Sara4994 commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +- Expecting components to create and maintain an "releases.yaml" file in their repositories particularly in manifest or config folders. The yaml can contain release details of the upstreams in format
+1 for a generic filename

2024-11-01 16:56 UTC, Sara4994 commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +- Create UX designs to display the list of information shared by the operator.
yep, removed

2024-11-01 16:58 UTC, Sara4994 commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +| ODH Platform Team             | Saravana Srinivasan   |   | ? |
added component team leads

2024-11-01 16:58 UTC, Sara4994 commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +# Open Data Hub - Map component upstream versions to RHOAI releases
yep, have changed this

2024-11-01 16:59 UTC, Sara4994 commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +- Expecting components to create and maintain an "releases.yaml" file in their repositories particularly in manifest or config folders. The yaml can contain release details of the upstreams in format
have changed the file name to odh_metadata.yaml

2024-11-04 08:08 UTC, lburgazzoli commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +- Expecting components to create and maintain an "odh_metadata.yaml" file in their repositories particularly in manifest or config folders. The yaml can contain release details of the upstreams in fo
I would try to make the location of the file as stable as possible so ideally it should always be in a specific folder to reduce variance among how the odh operator handles the various components.

2024-11-04 12:04 UTC, Sara4994 commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +- Expecting components to create and maintain an "odh_metadata.yaml" file in their repositories particularly in manifest or config folders. The yaml can contain release details of the upstreams in fo
In my understanding, components have just got either config or manifest folder, not both. for example kuberay has config [folder](https://github.com/opendatahub-io/kuberay/tree/dev/config)  in them and no manifests. and [getallManifests](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/get_all_manifests.sh) reads/downloads from the respective folders.

2024-11-05 07:07 UTC, lburgazzoli commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +- Expecting components to create and maintain an "odh_metadata.yaml" file in their repositories particularly in manifest or config folders. The yaml can contain release details of the upstreams in fo
Yep but as I read it, I can have both, a new component can even use a different folder for manifests. I would suggest to rephrase this sentence to stress that the file should be added to the same location as the manifests retrieved by the odh-operator (independently on the folder name), ideally on the root.

2024-11-05 12:49 UTC, Sara4994 commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +- Expecting components to create and maintain an "odh_metadata.yaml" file in their repositories particularly in manifest or config folders. The yaml can contain release details of the upstreams in fo
@lburgazzoli yea this makes more sense. I just rephrased it. Thanks :)

2024-11-12 16:16 UTC, Sara4994 commented
In accordance with the discussion happened in the channel [thread,](https://redhat-internal.slack.com/archives/C05NXTEHLGY/p1731327116001979) regarding the yaml file name, the name is now changed to component_metadata.yaml

2024-11-18 12:45 UTC, grdryn commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +RHOAISTRAT-327 Refinement Document
Should this link to that document?

2024-11-18 12:47 UTC, grdryn commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +Customers are expecting to know the list of upstream components and their versions they are using while using the product. There were already several requests from the customers wanting to know the c
```suggestion
Users are expecting to know the list of upstream components and their versions they are using while using the product. There were already several requests from users wanting to know the component versions during releases. 
```

^I think this might be a more upstream-friendly term?

2024-11-18 12:47 UTC, grdryn commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +- Have it displayed in the ODH operator, precisely in Data Science Cluster's components status.
```suggestion
- Have it displayed in the Data Science Cluster's components status.
```

2024-11-18 12:49 UTC, grdryn commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +- Expecting components team to create and maintain an "component_metadata.yaml" file in their repositories, in the same location as the manifests are being retrieved by the odh-operator, precisely in
```suggestion
- Component teams are expected to create and maintain a "component_metadata.yaml" file in their repositories, in the root of the manifests directory, which is retrieved by the ODH operator at build time. The yaml can contain release details of the upstreams in the format specified below.
```

2024-11-18 12:50 UTC, grdryn commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +- Develop code logics on the ODH operator to read through the component_metadata.yaml file present in the same location as the manifests are being retrieved by the odh-operator, precisely in the root
```suggestion
- Develop code logic on the ODH operator to read through the component_metadata.yaml file.
```

^Don't need to elaborate on the location of the file again, since that was just explained on line 29

2024-11-18 12:54 UTC, grdryn commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +- **Updating version details:** The component team is responsible for creating and maintaining the "component_metadata.yaml" file containing details of the upstreams and also, to promptly update the
This doesn't appear to be a question, so I'm not sure why it's in the "Open Questions" section?

2024-11-18 12:56 UTC, grdryn commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +- Initially, discussion happened to maintain this version information in an .env file. But, with further discussions and understandings, certain components have got multiple upstreams with them. Main
```suggestion
- Initially, it was proposed to maintain this version information in an .env file. But, with further discussions and understanding, certain components have multiple upstreams with them. Maintaining and fetching information about multiple upstream releases from an env file would be cumbersome, this pushed us to choose a yaml file where we can group details of each of the upstreams.
```

2024-11-18 17:28 UTC, Sara4994 commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +- Expecting components team to create and maintain an "component_metadata.yaml" file in their repositories, in the same location as the manifests are being retrieved by the odh-operator, precisely in
@grdryn Here some components keep their manifests in "config" directory, so thinking to rewrite a bit, like this "in the root of the directory from where the manifests are retrieved by the ODH operator at build time." wdyt?

2024-11-18 18:16 UTC, grdryn approved these changes
Looks reasonable to me, but I doubt my review is considered binding here. Does there need to be an approval from each of the groups in the "Stakeholder impacts" section?

2024-11-18 18:16 UTC, grdryn commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +Users are expecting to know the list of upstream components and their versions they are using while using the product. There were already several requests from the customers wanting to know the compo
```suggestion
Users are expecting to know the list of upstream components and their versions they are using while using the product. There were already several requests from users wanting to know the component versions during releases. 
```

You got one, but not the other :slightly_smiling_face:

2024-11-18 18:20 UTC, grdryn commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +- Expecting components team to create and maintain an "component_metadata.yaml" file in their repositories, in the same location as the manifests are being retrieved by the odh-operator, precisely in
> "in the root of the directory from where the manifests are retrieved by the ODH operator at build time."

:+1: 

/me wonders if we've got a common term for this location? :thinking: I guess from the get_all_manifests.sh it's "source-folder", but that might just be an internal implementation detail https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/get_all_manifests.sh#L7

2024-11-19 08:11 UTC, Sara4994 commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +Users are expecting to know the list of upstream components and their versions they are using while using the product. There were already several requests from the customers wanting to know the compo
oopss, yea just changed it. Thanks :)

2024-11-20 14:13 UTC, andrewballantyne commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +| ODH Dashboard Team        | @andrewballantyne                                               |            | y         |
This LGTM from a design perspective. 👍 

cc @ederign

2024-11-21 17:04 UTC, VaishnaviHire commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +    repositoryurl:
Hi @harshad16 , just including the yaml file in the folder should be enough

2024-11-21 18:20 UTC, harshad16 commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +    repositoryurl:
ack, thanks @VaishnaviHire and @Sara4994 for clearing all my doubts.

2024-11-21 18:21 UTC, harshad16 commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +| IDE Team                  | @harshad16                                                      |            | y         |
lgtm for design :+1:

2024-11-25 14:46 UTC, Xaenalt requested changes
One nit on language, other than that LGTM

2024-11-25 14:46 UTC, Xaenalt commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +Users are expecting to know the list of upstream components and their versions they are using while using the product. There were already several requests from users wanting to know the component ver
"While they are using the product" is incorrect for this ADR. We are telling them what we shipped, not what is running on the cluster

2024-11-25 14:50 UTC, Sara4994 commented on architecture-decision-records/operator/ODH-ADR-Operator-0007-components-version-mapping.md
> +Users are expecting to know the list of upstream components and their versions they are using while using the product. There were already several requests from users wanting to know the component ver
@Xaenalt yep, makes sense. Corrected it 👍

2024-11-25 14:51 UTC, Xaenalt approved these changes
LGTM

2024-11-26 05:59 UTC, vaibhavjainwiz commented
@Sara4994 Could you please also add ServingRuntime team in Stake holder impacted.

2024-11-26 09:17 UTC, vaibhavjainwiz commented
/lgtm

2024-11-26 09:18 UTC, vaibhavjainwiz approved these changes

2024-12-02 15:28 UTC, etirelli approved these changes

2024-12-02 15:28 UTC, merged