Added Feature Store architecture documentation
opendatahub-io/architecture-decision-records pull request #81
Opened 2024-12-17 21:57 UTC by redhatHameed

## Description

## How Has This Been Tested?

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2024-12-18 18:12 UTC, franciscojavierarceo reviewed
Is there a reason we don't put this upstream?

2024-12-19 14:33 UTC, etirelli commented
@franciscojavierarceo we can add all the relevant info/docs upstream, but we do need the architecture documentation of Feast/Feature Store in OpenShift AI here, to cover the gaps (integration into the platform) and fulfill the documentation requirements for the product.

2024-12-20 16:25 UTC, accorvin commented on documentation/arch-overview.md
> +    - To be done
@redhatHameed can you create a Jira issue tracking filling this in so that we don't forget to do this later?

2024-12-20 16:29 UTC, accorvin commented on documentation/components/feature_store/README.md
> +3. [**Registry**](https://docs.feast.dev/getting-started/components/online-store): Used to keep track of feature store definitions and state (optionally backed by GCS or S3 based persistent storage).
What kind of repository is meant in "stored in repositories?" Git repositories or feature repositories? Let's be explicit here.

2024-12-20 16:30 UTC, accorvin commented on documentation/components/feature_store/README.md
> +2. [**Online Store**](https://docs.feast.dev/getting-started/components/offline-store): Used for serving features at low-latency in production.
Rather than "at low-latency in production" maybe word this as "at low-latency for inference requests in production" so that we're very clear on what is meant by "in production"

2024-12-20 16:32 UTC, accorvin commented on documentation/components/feature_store/README.md
> +## Components
We should include the feature store controller/operator in this list of components.

2024-12-20 16:34 UTC, accorvin commented on documentation/components/feature_store/README.md
> +2. [**Online Store**](https://docs.feast.dev/getting-started/components/offline-store): Used for serving features at low-latency in production.
Somewhere in this document we should mention the backing storage for the online store and what is the default in RHOAI

2024-12-20 19:50 UTC, redhatHameed commented on documentation/arch-overview.md
> +    - To be done
Jira created [RHOAIENG-17245](https://issues.redhat.com/browse/RHOAIENG-17245)

2024-12-20 19:51 UTC, redhatHameed commented on documentation/components/feature_store/README.md
> +3. [**Registry**](https://docs.feast.dev/getting-started/components/online-store): Used to keep track of feature store definitions and state (optionally backed by GCS or S3 based persistent storage).
This is feature repository, updated accordingly.

2024-12-20 19:51 UTC, redhatHameed commented on documentation/components/feature_store/README.md
> +2. [**Online Store**](https://docs.feast.dev/getting-started/components/offline-store): Used for serving features at low-latency in production.
Done as suggested.

2024-12-20 19:52 UTC, redhatHameed commented on documentation/components/feature_store/README.md
> +## Components
Feature Store Controller/Operator included in the component list.

2024-12-20 19:53 UTC, redhatHameed commented on documentation/components/feature_store/README.md
> +1. [**Offline Store**](https://docs.feast.dev/getting-started/components/registry) : Used for historical feature extraction used in model training.
Thanks for catching this fixed now.

2024-12-20 19:57 UTC, franciscojavierarceo commented on documentation/components/feature_store/README.md
> +
```suggestion
https://rtd.feast.dev/
```

2024-12-20 19:59 UTC, franciscojavierarceo commented on documentation/components/feature_store/README.md
> +
Should add a component about the Feature Server. https://github.com/feast-dev/feast/pull/4868

2024-12-20 20:00 UTC, franciscojavierarceo commented on documentation/components/feature_store/README.md
> +The UI Dashboard initializes/Create the FeatureStore CR and sets config for feature services for data ingestion, transformation, and storage.
```suggestion
The UI Dashboard initializes/Creates the FeatureStore CR and sets the config for feature services used for data ingestion, transformation, and storage.
```

2024-12-20 20:01 UTC, redhatHameed commented on documentation/components/feature_store/README.md
> +2. [**Online Store**](https://docs.feast.dev/getting-started/components/offline-store): Used for serving features at low-latency in production.
If I recall correctly, there was discussion to use MariaDB in RHOAI by default. However, let's double-check this with @etirelli

2024-12-20 20:03 UTC, franciscojavierarceo commented on documentation/components/feature_store/README.md
> +Once pre-processed, the data is sent to Feast via batch or streaming data pipelines. Feast connectors simplify integration with various data sources (batch, stream, and on-demand).
Data can be sent to Feast either pre-processed (e.g., via batch or streaming data pipelines) or raw and transformed by the Feast feature server during data ingestion (i.e., transformed prior to being written to the online store). Feast simplifies the integration with various data sources by providing an opinionated yet flexible API.

2024-12-20 20:03 UTC, franciscojavierarceo commented on documentation/components/feature_store/README.md
> +Once pre-processed, the data is sent to Feast via batch or streaming data pipelines. Feast connectors simplify integration with various data sources (batch, stream, and on-demand).
```suggestion
Data can be sent to Feast either pre-processed (e.g., via batch or streaming data pipelines) or raw and transformed by the Feast feature server during data ingestion (i.e., transformed prior to being written to the online store). Feast simplifies the integration with various data sources by providing an opinionated yet flexible API.
```

2024-12-20 20:04 UTC, franciscojavierarceo commented on documentation/components/feature_store/README.md
> +2. [**Online Store**](https://docs.feast.dev/getting-started/components/offline-store): Used for serving features at low-latency in production.
Yes, that was the one we had originally considered but it may be a good idea for us to go with Milvus. 😅

2024-12-20 20:08 UTC, franciscojavierarceo commented on documentation/components/feature_store/README.md
> +**Online Store:** Low-latency storage (in-memory/cache) for frequently accessed features required during real-time inference.
```suggestion
**Offline Store**: A lower-cost, persistent storage system (e.g., data warehouse) optimized for storing large volumes of historical feature data used in model training and batch scoring. It prioritizes storage efficiency over low-latency access.

**Online Store**: A higher-cost, low-latency storage system (e.g., in-memory database or cache) designed to provide rapid access to frequently used features during real-time inference, optimizing for speed and responsiveness.
```

2024-12-20 20:09 UTC, franciscojavierarceo commented on documentation/components/feature_store/README.md
> +**Feature Registry:** Metadata storage to track feature definitions and their transformations.
```suggestion
**Feature Registry:** Metadata storage to track feature definitions, feature transformations, and feature metadata.
```

2024-12-20 20:11 UTC, franciscojavierarceo commented on documentation/components/feature_store/README.md
> +The trained model is validated on a hold-out dataset to assess its accuracy and generalizability.
```suggestion
The trained model is validated on a hold-out dataset to assess its accuracy, generalizability, and impact to its domain.
```

2024-12-20 20:13 UTC, franciscojavierarceo commented on documentation/components/feature_store/README.md
> +Applications send inference requests to the Model Server. The server retrieves real-time features from the Online Store and generates predictions using the deployed model.
It should be noted that this is one way to do it.  An alternative is to flip it and use the feature store to cache a prediction.

https://docs.feast.dev/getting-started/architecture/model-inference#id-3.-online-model-inference-with-online-features-and-cached-predictions

2024-12-20 20:14 UTC, franciscojavierarceo commented on documentation/components/feature_store/README.md
> +Applications send inference requests to the Model Server. The server retrieves real-time features from the Online Store and generates predictions using the deployed model.
I mention this because for latency sensitive applications, this is often a good choice.

2024-12-20 20:14 UTC, franciscojavierarceo requested changes
Some small nits but looks great!

2024-12-20 21:01 UTC, redhatHameed commented on documentation/components/feature_store/README.md
> +
Added under `Feature Store Controller/Operator` along with the other servers (Offline/Registry). Let me know if that makes sense.

2024-12-20 21:40 UTC, franciscojavierarceo commented on documentation/components/feature_store/README.md
> +
I'd recommend adding it explicitly as it's a core component for actually serving the online store.

2024-12-20 23:55 UTC, redhatHameed commented on documentation/components/feature_store/README.md
> +
Got it. Added. Please take a look when get time. Thanks!

2024-12-21 02:11 UTC, franciscojavierarceo commented on documentation/components/feature_store/README.md
> +Applications send inference requests to the Model Server. The server retrieves real-time features from the Online Store and generates predictions using the deployed model.
```suggestion
There are three ways to orchestrate inference requests. 
    1. The applications sends an inference requests to the Model Server and the Model Server retrieves real-time features from the Feature Server and generates predictions using the retrieved features and deployed model.
    2. The application sends an inference request to the Feature Server and the Feature Server sends the features to the Model Server and generates predictions using the deployed model.
    3. The application sends a request to the Feature Server and sends the features to the Model Server whcih generates predictions using the deployed model.
```

2024-12-23 03:22 UTC, franciscojavierarceo approved these changes

2024-12-23 17:06 UTC, redhatHameed commented
@opendatahub-io/architects can you review this once get time. Thanks

2024-12-30 15:15 UTC, etirelli approved these changes

2024-12-30 15:15 UTC, etirelli commented
I will merge the PR as is, and we can iteratively improve the docs on a new PR.

2024-12-30 15:16 UTC, merged